#!/bin/bash
### BEGIN INIT INFO
# Provides:          song_processor
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Song processor Startup Program
# Description:       Runs song processor program at startup.
### END INIT INFO

case "$1" in
  start)
    /home/root/fifo_write songs/replay_1.wav &
    ;;
  stop)
    killall yourprogram
    ;;
  *)
    echo "Usage: /etc/init.d/song_processor {start|stop}"
    exit 1
    ;;
esac

exit 0