#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'reloj_soc' in
 * file './reloj_soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'FIFO', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_COMPONENT_NAME FIFO
#define FIFO_BASE 0x5000
#define FIFO_SPAN 4
#define FIFO_END 0x5003
#define FIFO_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_BITS_PER_SYMBOL 16
#define FIFO_CHANNEL_WIDTH 8
#define FIFO_ERROR_WIDTH 8
#define FIFO_FIFO_DEPTH 256
#define FIFO_SINGLE_CLOCK_MODE 1
#define FIFO_SYMBOLS_PER_BEAT 2
#define FIFO_USE_AVALONMM_READ_SLAVE 1
#define FIFO_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_USE_AVALONST_SINK 0
#define FIFO_USE_AVALONST_SOURCE 0
#define FIFO_USE_BACKPRESSURE 1
#define FIFO_USE_IRQ 1
#define FIFO_USE_PACKET 1
#define FIFO_USE_READ_CONTROL 0
#define FIFO_USE_REGISTER 0
#define FIFO_USE_WRITE_CONTROL 1


#endif /* _ALTERA_HPS_H_ */
