// MTL2.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module MTL2 (
		input  wire       clk_clk,       //   clk.clk
		output wire       mtl2_CLK,      //  mtl2.CLK
		output wire       mtl2_HS,       //      .HS
		output wire       mtl2_VS,       //      .VS
		output wire       mtl2_DATA_EN,  //      .DATA_EN
		output wire [7:0] mtl2_R,        //      .R
		output wire [7:0] mtl2_G,        //      .G
		output wire [7:0] mtl2_B,        //      .B
		input  wire       reset_reset_n  // reset.reset_n
	);

	wire         char_buffer_avalon_char_source_valid;                               // CHAR_BUFFER:stream_valid -> MTL2_DRIVER:valid
	wire  [29:0] char_buffer_avalon_char_source_data;                                // CHAR_BUFFER:stream_data -> MTL2_DRIVER:data
	wire         char_buffer_avalon_char_source_ready;                               // MTL2_DRIVER:ready -> CHAR_BUFFER:stream_ready
	wire         char_buffer_avalon_char_source_startofpacket;                       // CHAR_BUFFER:stream_startofpacket -> MTL2_DRIVER:startofpacket
	wire         char_buffer_avalon_char_source_endofpacket;                         // CHAR_BUFFER:stream_endofpacket -> MTL2_DRIVER:endofpacket
	wire         mtl2_clk_lcd_clk_clk;                                               // MTL2_CLK:lcd_clk_clk -> [CHAR_BUFFER:clk, MTL2_DRIVER:clk, mm_interconnect_0:MTL2_CLK_lcd_clk_clk, rst_controller:clk]
	wire  [31:0] niosii_data_master_readdata;                                        // mm_interconnect_0:NIOSII_data_master_readdata -> NIOSII:d_readdata
	wire         niosii_data_master_waitrequest;                                     // mm_interconnect_0:NIOSII_data_master_waitrequest -> NIOSII:d_waitrequest
	wire         niosii_data_master_debugaccess;                                     // NIOSII:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOSII_data_master_debugaccess
	wire  [17:0] niosii_data_master_address;                                         // NIOSII:d_address -> mm_interconnect_0:NIOSII_data_master_address
	wire   [3:0] niosii_data_master_byteenable;                                      // NIOSII:d_byteenable -> mm_interconnect_0:NIOSII_data_master_byteenable
	wire         niosii_data_master_read;                                            // NIOSII:d_read -> mm_interconnect_0:NIOSII_data_master_read
	wire         niosii_data_master_write;                                           // NIOSII:d_write -> mm_interconnect_0:NIOSII_data_master_write
	wire  [31:0] niosii_data_master_writedata;                                       // NIOSII:d_writedata -> mm_interconnect_0:NIOSII_data_master_writedata
	wire  [31:0] niosii_instruction_master_readdata;                                 // mm_interconnect_0:NIOSII_instruction_master_readdata -> NIOSII:i_readdata
	wire         niosii_instruction_master_waitrequest;                              // mm_interconnect_0:NIOSII_instruction_master_waitrequest -> NIOSII:i_waitrequest
	wire  [17:0] niosii_instruction_master_address;                                  // NIOSII:i_address -> mm_interconnect_0:NIOSII_instruction_master_address
	wire         niosii_instruction_master_read;                                     // NIOSII:i_read -> mm_interconnect_0:NIOSII_instruction_master_read
	wire         mm_interconnect_0_char_buffer_avalon_char_buffer_slave_chipselect;  // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_chipselect -> CHAR_BUFFER:buf_chipselect
	wire   [7:0] mm_interconnect_0_char_buffer_avalon_char_buffer_slave_readdata;    // CHAR_BUFFER:buf_readdata -> mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_readdata
	wire         mm_interconnect_0_char_buffer_avalon_char_buffer_slave_waitrequest; // CHAR_BUFFER:buf_waitrequest -> mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_waitrequest
	wire  [10:0] mm_interconnect_0_char_buffer_avalon_char_buffer_slave_address;     // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_address -> CHAR_BUFFER:buf_address
	wire         mm_interconnect_0_char_buffer_avalon_char_buffer_slave_read;        // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_read -> CHAR_BUFFER:buf_read
	wire   [0:0] mm_interconnect_0_char_buffer_avalon_char_buffer_slave_byteenable;  // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_byteenable -> CHAR_BUFFER:buf_byteenable
	wire         mm_interconnect_0_char_buffer_avalon_char_buffer_slave_write;       // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_write -> CHAR_BUFFER:buf_write
	wire   [7:0] mm_interconnect_0_char_buffer_avalon_char_buffer_slave_writedata;   // mm_interconnect_0:CHAR_BUFFER_avalon_char_buffer_slave_writedata -> CHAR_BUFFER:buf_writedata
	wire         mm_interconnect_0_char_buffer_avalon_char_control_slave_chipselect; // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_chipselect -> CHAR_BUFFER:ctrl_chipselect
	wire  [31:0] mm_interconnect_0_char_buffer_avalon_char_control_slave_readdata;   // CHAR_BUFFER:ctrl_readdata -> mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_readdata
	wire   [0:0] mm_interconnect_0_char_buffer_avalon_char_control_slave_address;    // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_address -> CHAR_BUFFER:ctrl_address
	wire         mm_interconnect_0_char_buffer_avalon_char_control_slave_read;       // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_read -> CHAR_BUFFER:ctrl_read
	wire   [3:0] mm_interconnect_0_char_buffer_avalon_char_control_slave_byteenable; // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_byteenable -> CHAR_BUFFER:ctrl_byteenable
	wire         mm_interconnect_0_char_buffer_avalon_char_control_slave_write;      // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_write -> CHAR_BUFFER:ctrl_write
	wire  [31:0] mm_interconnect_0_char_buffer_avalon_char_control_slave_writedata;  // mm_interconnect_0:CHAR_BUFFER_avalon_char_control_slave_writedata -> CHAR_BUFFER:ctrl_writedata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;           // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;             // JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest;          // JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;              // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;                 // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> JTAG_UART:av_read_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;                // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> JTAG_UART:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;            // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	wire  [31:0] mm_interconnect_0_niosii_debug_mem_slave_readdata;                  // NIOSII:debug_mem_slave_readdata -> mm_interconnect_0:NIOSII_debug_mem_slave_readdata
	wire         mm_interconnect_0_niosii_debug_mem_slave_waitrequest;               // NIOSII:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOSII_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_niosii_debug_mem_slave_debugaccess;               // mm_interconnect_0:NIOSII_debug_mem_slave_debugaccess -> NIOSII:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_niosii_debug_mem_slave_address;                   // mm_interconnect_0:NIOSII_debug_mem_slave_address -> NIOSII:debug_mem_slave_address
	wire         mm_interconnect_0_niosii_debug_mem_slave_read;                      // mm_interconnect_0:NIOSII_debug_mem_slave_read -> NIOSII:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_niosii_debug_mem_slave_byteenable;                // mm_interconnect_0:NIOSII_debug_mem_slave_byteenable -> NIOSII:debug_mem_slave_byteenable
	wire         mm_interconnect_0_niosii_debug_mem_slave_write;                     // mm_interconnect_0:NIOSII_debug_mem_slave_write -> NIOSII:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_niosii_debug_mem_slave_writedata;                 // mm_interconnect_0:NIOSII_debug_mem_slave_writedata -> NIOSII:debug_mem_slave_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                                // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                                  // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [13:0] mm_interconnect_0_ram_s1_address;                                   // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                                // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                                     // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                                 // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                                     // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire         irq_mapper_receiver0_irq;                                           // JTAG_UART:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] niosii_irq_irq;                                                     // irq_mapper:sender_irq -> NIOSII:irq
	wire         rst_controller_reset_out_reset;                                     // rst_controller:reset_out -> [CHAR_BUFFER:reset, MTL2_DRIVER:reset, mm_interconnect_0:CHAR_BUFFER_reset_reset_bridge_in_reset_reset]
	wire         mtl2_clk_reset_source_reset;                                        // MTL2_CLK:reset_source_reset -> rst_controller:reset_in0
	wire         rst_controller_001_reset_out_reset;                                 // rst_controller_001:reset_out -> [JTAG_UART:rst_n, NIOSII:reset_n, RAM:reset, irq_mapper:reset, mm_interconnect_0:NIOSII_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_001_reset_out_reset_req;                             // rst_controller_001:reset_req -> [NIOSII:reset_req, RAM:reset_req, rst_translator:reset_req_in]

	MTL2_CHAR_BUFFER char_buffer (
		.clk                  (mtl2_clk_lcd_clk_clk),                                               //                       clk.clk
		.reset                (rst_controller_reset_out_reset),                                     //                     reset.reset
		.ctrl_address         (mm_interconnect_0_char_buffer_avalon_char_control_slave_address),    // avalon_char_control_slave.address
		.ctrl_byteenable      (mm_interconnect_0_char_buffer_avalon_char_control_slave_byteenable), //                          .byteenable
		.ctrl_chipselect      (mm_interconnect_0_char_buffer_avalon_char_control_slave_chipselect), //                          .chipselect
		.ctrl_read            (mm_interconnect_0_char_buffer_avalon_char_control_slave_read),       //                          .read
		.ctrl_write           (mm_interconnect_0_char_buffer_avalon_char_control_slave_write),      //                          .write
		.ctrl_writedata       (mm_interconnect_0_char_buffer_avalon_char_control_slave_writedata),  //                          .writedata
		.ctrl_readdata        (mm_interconnect_0_char_buffer_avalon_char_control_slave_readdata),   //                          .readdata
		.buf_byteenable       (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_byteenable),  //  avalon_char_buffer_slave.byteenable
		.buf_chipselect       (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_chipselect),  //                          .chipselect
		.buf_read             (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_read),        //                          .read
		.buf_write            (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_write),       //                          .write
		.buf_writedata        (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_writedata),   //                          .writedata
		.buf_readdata         (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_readdata),    //                          .readdata
		.buf_waitrequest      (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_waitrequest), //                          .waitrequest
		.buf_address          (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_address),     //                          .address
		.stream_ready         (char_buffer_avalon_char_source_ready),                               //        avalon_char_source.ready
		.stream_startofpacket (char_buffer_avalon_char_source_startofpacket),                       //                          .startofpacket
		.stream_endofpacket   (char_buffer_avalon_char_source_endofpacket),                         //                          .endofpacket
		.stream_valid         (char_buffer_avalon_char_source_valid),                               //                          .valid
		.stream_data          (char_buffer_avalon_char_source_data)                                 //                          .data
	);

	MTL2_JTAG_UART jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_001_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	MTL2_MTL2_CLK mtl2_clk_inst (
		.ref_clk_clk        (clk_clk),                     //      ref_clk.clk
		.ref_reset_reset    (~reset_reset_n),              //    ref_reset.reset
		.lcd_clk_clk        (mtl2_clk_lcd_clk_clk),        //      lcd_clk.clk
		.reset_source_reset (mtl2_clk_reset_source_reset)  // reset_source.reset
	);

	MTL2_MTL2_DRIVER mtl2_driver (
		.clk           (mtl2_clk_lcd_clk_clk),                         //                clk.clk
		.reset         (rst_controller_reset_out_reset),               //              reset.reset
		.data          (char_buffer_avalon_char_source_data),          //    avalon_vga_sink.data
		.startofpacket (char_buffer_avalon_char_source_startofpacket), //                   .startofpacket
		.endofpacket   (char_buffer_avalon_char_source_endofpacket),   //                   .endofpacket
		.valid         (char_buffer_avalon_char_source_valid),         //                   .valid
		.ready         (char_buffer_avalon_char_source_ready),         //                   .ready
		.VGA_CLK       (mtl2_CLK),                                     // external_interface.export
		.VGA_HS        (mtl2_HS),                                      //                   .export
		.VGA_VS        (mtl2_VS),                                      //                   .export
		.VGA_DATA_EN   (mtl2_DATA_EN),                                 //                   .export
		.VGA_R         (mtl2_R),                                       //                   .export
		.VGA_G         (mtl2_G),                                       //                   .export
		.VGA_B         (mtl2_B)                                        //                   .export
	);

	MTL2_NIOSII niosii (
		.clk                                 (clk_clk),                                              //                       clk.clk
		.reset_n                             (~rst_controller_001_reset_out_reset),                  //                     reset.reset_n
		.reset_req                           (rst_controller_001_reset_out_reset_req),               //                          .reset_req
		.d_address                           (niosii_data_master_address),                           //               data_master.address
		.d_byteenable                        (niosii_data_master_byteenable),                        //                          .byteenable
		.d_read                              (niosii_data_master_read),                              //                          .read
		.d_readdata                          (niosii_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (niosii_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (niosii_data_master_write),                             //                          .write
		.d_writedata                         (niosii_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (niosii_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (niosii_instruction_master_address),                    //        instruction_master.address
		.i_read                              (niosii_instruction_master_read),                       //                          .read
		.i_readdata                          (niosii_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (niosii_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (niosii_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (),                                                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_niosii_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_niosii_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_niosii_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_niosii_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_niosii_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_niosii_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_niosii_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_niosii_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                      // custom_instruction_master.readra
	);

	MTL2_RAM ram (
		.clk        (clk_clk),                                //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),       //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),         //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect),    //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),         //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),      //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),     //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable),    //       .byteenable
		.reset      (rst_controller_001_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_001_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                    // (terminated)
	);

	MTL2_mm_interconnect_0 mm_interconnect_0 (
		.CLK_clk_clk                                      (clk_clk),                                                            //                                 CLK_clk.clk
		.MTL2_CLK_lcd_clk_clk                             (mtl2_clk_lcd_clk_clk),                                               //                        MTL2_CLK_lcd_clk.clk
		.CHAR_BUFFER_reset_reset_bridge_in_reset_reset    (rst_controller_reset_out_reset),                                     // CHAR_BUFFER_reset_reset_bridge_in_reset.reset
		.NIOSII_reset_reset_bridge_in_reset_reset         (rst_controller_001_reset_out_reset),                                 //      NIOSII_reset_reset_bridge_in_reset.reset
		.NIOSII_data_master_address                       (niosii_data_master_address),                                         //                      NIOSII_data_master.address
		.NIOSII_data_master_waitrequest                   (niosii_data_master_waitrequest),                                     //                                        .waitrequest
		.NIOSII_data_master_byteenable                    (niosii_data_master_byteenable),                                      //                                        .byteenable
		.NIOSII_data_master_read                          (niosii_data_master_read),                                            //                                        .read
		.NIOSII_data_master_readdata                      (niosii_data_master_readdata),                                        //                                        .readdata
		.NIOSII_data_master_write                         (niosii_data_master_write),                                           //                                        .write
		.NIOSII_data_master_writedata                     (niosii_data_master_writedata),                                       //                                        .writedata
		.NIOSII_data_master_debugaccess                   (niosii_data_master_debugaccess),                                     //                                        .debugaccess
		.NIOSII_instruction_master_address                (niosii_instruction_master_address),                                  //               NIOSII_instruction_master.address
		.NIOSII_instruction_master_waitrequest            (niosii_instruction_master_waitrequest),                              //                                        .waitrequest
		.NIOSII_instruction_master_read                   (niosii_instruction_master_read),                                     //                                        .read
		.NIOSII_instruction_master_readdata               (niosii_instruction_master_readdata),                                 //                                        .readdata
		.CHAR_BUFFER_avalon_char_buffer_slave_address     (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_address),     //    CHAR_BUFFER_avalon_char_buffer_slave.address
		.CHAR_BUFFER_avalon_char_buffer_slave_write       (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_write),       //                                        .write
		.CHAR_BUFFER_avalon_char_buffer_slave_read        (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_read),        //                                        .read
		.CHAR_BUFFER_avalon_char_buffer_slave_readdata    (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_readdata),    //                                        .readdata
		.CHAR_BUFFER_avalon_char_buffer_slave_writedata   (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_writedata),   //                                        .writedata
		.CHAR_BUFFER_avalon_char_buffer_slave_byteenable  (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_byteenable),  //                                        .byteenable
		.CHAR_BUFFER_avalon_char_buffer_slave_waitrequest (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_waitrequest), //                                        .waitrequest
		.CHAR_BUFFER_avalon_char_buffer_slave_chipselect  (mm_interconnect_0_char_buffer_avalon_char_buffer_slave_chipselect),  //                                        .chipselect
		.CHAR_BUFFER_avalon_char_control_slave_address    (mm_interconnect_0_char_buffer_avalon_char_control_slave_address),    //   CHAR_BUFFER_avalon_char_control_slave.address
		.CHAR_BUFFER_avalon_char_control_slave_write      (mm_interconnect_0_char_buffer_avalon_char_control_slave_write),      //                                        .write
		.CHAR_BUFFER_avalon_char_control_slave_read       (mm_interconnect_0_char_buffer_avalon_char_control_slave_read),       //                                        .read
		.CHAR_BUFFER_avalon_char_control_slave_readdata   (mm_interconnect_0_char_buffer_avalon_char_control_slave_readdata),   //                                        .readdata
		.CHAR_BUFFER_avalon_char_control_slave_writedata  (mm_interconnect_0_char_buffer_avalon_char_control_slave_writedata),  //                                        .writedata
		.CHAR_BUFFER_avalon_char_control_slave_byteenable (mm_interconnect_0_char_buffer_avalon_char_control_slave_byteenable), //                                        .byteenable
		.CHAR_BUFFER_avalon_char_control_slave_chipselect (mm_interconnect_0_char_buffer_avalon_char_control_slave_chipselect), //                                        .chipselect
		.JTAG_UART_avalon_jtag_slave_address              (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),              //             JTAG_UART_avalon_jtag_slave.address
		.JTAG_UART_avalon_jtag_slave_write                (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),                //                                        .write
		.JTAG_UART_avalon_jtag_slave_read                 (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),                 //                                        .read
		.JTAG_UART_avalon_jtag_slave_readdata             (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),             //                                        .readdata
		.JTAG_UART_avalon_jtag_slave_writedata            (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),            //                                        .writedata
		.JTAG_UART_avalon_jtag_slave_waitrequest          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest),          //                                        .waitrequest
		.JTAG_UART_avalon_jtag_slave_chipselect           (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),           //                                        .chipselect
		.NIOSII_debug_mem_slave_address                   (mm_interconnect_0_niosii_debug_mem_slave_address),                   //                  NIOSII_debug_mem_slave.address
		.NIOSII_debug_mem_slave_write                     (mm_interconnect_0_niosii_debug_mem_slave_write),                     //                                        .write
		.NIOSII_debug_mem_slave_read                      (mm_interconnect_0_niosii_debug_mem_slave_read),                      //                                        .read
		.NIOSII_debug_mem_slave_readdata                  (mm_interconnect_0_niosii_debug_mem_slave_readdata),                  //                                        .readdata
		.NIOSII_debug_mem_slave_writedata                 (mm_interconnect_0_niosii_debug_mem_slave_writedata),                 //                                        .writedata
		.NIOSII_debug_mem_slave_byteenable                (mm_interconnect_0_niosii_debug_mem_slave_byteenable),                //                                        .byteenable
		.NIOSII_debug_mem_slave_waitrequest               (mm_interconnect_0_niosii_debug_mem_slave_waitrequest),               //                                        .waitrequest
		.NIOSII_debug_mem_slave_debugaccess               (mm_interconnect_0_niosii_debug_mem_slave_debugaccess),               //                                        .debugaccess
		.RAM_s1_address                                   (mm_interconnect_0_ram_s1_address),                                   //                                  RAM_s1.address
		.RAM_s1_write                                     (mm_interconnect_0_ram_s1_write),                                     //                                        .write
		.RAM_s1_readdata                                  (mm_interconnect_0_ram_s1_readdata),                                  //                                        .readdata
		.RAM_s1_writedata                                 (mm_interconnect_0_ram_s1_writedata),                                 //                                        .writedata
		.RAM_s1_byteenable                                (mm_interconnect_0_ram_s1_byteenable),                                //                                        .byteenable
		.RAM_s1_chipselect                                (mm_interconnect_0_ram_s1_chipselect),                                //                                        .chipselect
		.RAM_s1_clken                                     (mm_interconnect_0_ram_s1_clken)                                      //                                        .clken
	);

	MTL2_irq_mapper irq_mapper (
		.clk           (clk_clk),                            //       clk.clk
		.reset         (rst_controller_001_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.sender_irq    (niosii_irq_irq)                      //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (mtl2_clk_reset_source_reset),    // reset_in0.reset
		.clk            (mtl2_clk_lcd_clk_clk),           //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_in1      (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
