// reloj_soc_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module reloj_soc_mm_interconnect_2 (
		input  wire        CLK_clk_clk,                                  //                                CLK_clk.clk
		input  wire        MEM_BRIDGE_reset_reset_bridge_in_reset_reset, // MEM_BRIDGE_reset_reset_bridge_in_reset.reset
		input  wire [9:0]  MEM_BRIDGE_m0_address,                        //                          MEM_BRIDGE_m0.address
		output wire        MEM_BRIDGE_m0_waitrequest,                    //                                       .waitrequest
		input  wire [0:0]  MEM_BRIDGE_m0_burstcount,                     //                                       .burstcount
		input  wire [3:0]  MEM_BRIDGE_m0_byteenable,                     //                                       .byteenable
		input  wire        MEM_BRIDGE_m0_read,                           //                                       .read
		output wire [31:0] MEM_BRIDGE_m0_readdata,                       //                                       .readdata
		output wire        MEM_BRIDGE_m0_readdatavalid,                  //                                       .readdatavalid
		input  wire        MEM_BRIDGE_m0_write,                          //                                       .write
		input  wire [31:0] MEM_BRIDGE_m0_writedata,                      //                                       .writedata
		input  wire        MEM_BRIDGE_m0_debugaccess,                    //                                       .debugaccess
		output wire        FIFO_in_write,                                //                                FIFO_in.write
		output wire [31:0] FIFO_in_writedata,                            //                                       .writedata
		input  wire        FIFO_in_waitrequest                           //                                       .waitrequest
	);

	wire         mem_bridge_m0_translator_avalon_universal_master_0_waitrequest;   // FIFO_in_translator:uav_waitrequest -> MEM_BRIDGE_m0_translator:uav_waitrequest
	wire  [31:0] mem_bridge_m0_translator_avalon_universal_master_0_readdata;      // FIFO_in_translator:uav_readdata -> MEM_BRIDGE_m0_translator:uav_readdata
	wire         mem_bridge_m0_translator_avalon_universal_master_0_debugaccess;   // MEM_BRIDGE_m0_translator:uav_debugaccess -> FIFO_in_translator:uav_debugaccess
	wire   [9:0] mem_bridge_m0_translator_avalon_universal_master_0_address;       // MEM_BRIDGE_m0_translator:uav_address -> FIFO_in_translator:uav_address
	wire         mem_bridge_m0_translator_avalon_universal_master_0_read;          // MEM_BRIDGE_m0_translator:uav_read -> FIFO_in_translator:uav_read
	wire   [3:0] mem_bridge_m0_translator_avalon_universal_master_0_byteenable;    // MEM_BRIDGE_m0_translator:uav_byteenable -> FIFO_in_translator:uav_byteenable
	wire         mem_bridge_m0_translator_avalon_universal_master_0_readdatavalid; // FIFO_in_translator:uav_readdatavalid -> MEM_BRIDGE_m0_translator:uav_readdatavalid
	wire         mem_bridge_m0_translator_avalon_universal_master_0_lock;          // MEM_BRIDGE_m0_translator:uav_lock -> FIFO_in_translator:uav_lock
	wire         mem_bridge_m0_translator_avalon_universal_master_0_write;         // MEM_BRIDGE_m0_translator:uav_write -> FIFO_in_translator:uav_write
	wire  [31:0] mem_bridge_m0_translator_avalon_universal_master_0_writedata;     // MEM_BRIDGE_m0_translator:uav_writedata -> FIFO_in_translator:uav_writedata
	wire   [2:0] mem_bridge_m0_translator_avalon_universal_master_0_burstcount;    // MEM_BRIDGE_m0_translator:uav_burstcount -> FIFO_in_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (10),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (10),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) mem_bridge_m0_translator (
		.clk                    (CLK_clk_clk),                                                      //                       clk.clk
		.reset                  (MEM_BRIDGE_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (mem_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (mem_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (mem_bridge_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (mem_bridge_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (mem_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (mem_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (mem_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (mem_bridge_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (mem_bridge_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (mem_bridge_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (mem_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (MEM_BRIDGE_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (MEM_BRIDGE_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (MEM_BRIDGE_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (MEM_BRIDGE_m0_byteenable),                                         //                          .byteenable
		.av_read                (MEM_BRIDGE_m0_read),                                               //                          .read
		.av_readdata            (MEM_BRIDGE_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (MEM_BRIDGE_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (MEM_BRIDGE_m0_write),                                              //                          .write
		.av_writedata           (MEM_BRIDGE_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (MEM_BRIDGE_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                             //               (terminated)
		.av_lock                (1'b0),                                                             //               (terminated)
		.uav_clken              (),                                                                 //               (terminated)
		.av_clken               (1'b1),                                                             //               (terminated)
		.uav_response           (2'b00),                                                            //               (terminated)
		.av_response            (),                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (10),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) fifo_in_translator (
		.clk                    (CLK_clk_clk),                                                      //                      clk.clk
		.reset                  (MEM_BRIDGE_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (mem_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (mem_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (mem_bridge_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (mem_bridge_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (mem_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (mem_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (mem_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (mem_bridge_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (mem_bridge_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (mem_bridge_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (mem_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_write               (FIFO_in_write),                                                    //      avalon_anti_slave_0.write
		.av_writedata           (FIFO_in_writedata),                                                //                         .writedata
		.av_waitrequest         (FIFO_in_waitrequest),                                              //                         .waitrequest
		.av_address             (),                                                                 //              (terminated)
		.av_read                (),                                                                 //              (terminated)
		.av_readdata            (32'b11011110101011011101111010101101),                             //              (terminated)
		.av_begintransfer       (),                                                                 //              (terminated)
		.av_beginbursttransfer  (),                                                                 //              (terminated)
		.av_burstcount          (),                                                                 //              (terminated)
		.av_byteenable          (),                                                                 //              (terminated)
		.av_readdatavalid       (1'b0),                                                             //              (terminated)
		.av_writebyteenable     (),                                                                 //              (terminated)
		.av_lock                (),                                                                 //              (terminated)
		.av_chipselect          (),                                                                 //              (terminated)
		.av_clken               (),                                                                 //              (terminated)
		.uav_clken              (1'b0),                                                             //              (terminated)
		.av_debugaccess         (),                                                                 //              (terminated)
		.av_outputenable        (),                                                                 //              (terminated)
		.uav_response           (),                                                                 //              (terminated)
		.av_response            (2'b00),                                                            //              (terminated)
		.uav_writeresponsevalid (),                                                                 //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                              //              (terminated)
	);

endmodule
