#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'reloj_soc' in
 * file './reloj_soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'RAM', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'RAM_'.
 * The prefix is the slave descriptor.
 */
#define RAM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define RAM_COMPONENT_NAME RAM
#define RAM_BASE 0x0
#define RAM_SPAN 8192
#define RAM_END 0x1fff
#define RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM_CONTENTS_INFO ""
#define RAM_DUAL_PORT 1
#define RAM_GUI_RAM_BLOCK_TYPE AUTO
#define RAM_INIT_CONTENTS_FILE reloj_soc_RAM
#define RAM_INIT_MEM_CONTENT 1
#define RAM_INSTANCE_ID NONE
#define RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM_RAM_BLOCK_TYPE AUTO
#define RAM_READ_DURING_WRITE_MODE DONT_CARE
#define RAM_SINGLE_CLOCK_OP 0
#define RAM_SIZE_MULTIPLE 1
#define RAM_SIZE_VALUE 8192
#define RAM_WRITABLE 1
#define RAM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define RAM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define RAM_MEMORY_INFO_GENERATE_HEX 1
#define RAM_MEMORY_INFO_HAS_BYTE_LANE 0
#define RAM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define RAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define RAM_MEMORY_INFO_MEM_INIT_FILENAME reloj_soc_RAM

/*
 * Macros for device 'FIFO', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_COMPONENT_NAME FIFO
#define FIFO_BASE 0x10000
#define FIFO_SPAN 4
#define FIFO_END 0x10003
#define FIFO_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_BITS_PER_SYMBOL 16
#define FIFO_CHANNEL_WIDTH 8
#define FIFO_ERROR_WIDTH 8
#define FIFO_FIFO_DEPTH 256
#define FIFO_SINGLE_CLOCK_MODE 1
#define FIFO_SYMBOLS_PER_BEAT 2
#define FIFO_USE_AVALONMM_READ_SLAVE 1
#define FIFO_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_USE_AVALONST_SINK 0
#define FIFO_USE_AVALONST_SOURCE 0
#define FIFO_USE_BACKPRESSURE 0
#define FIFO_USE_IRQ 1
#define FIFO_USE_PACKET 1
#define FIFO_USE_READ_CONTROL 0
#define FIFO_USE_REGISTER 0
#define FIFO_USE_WRITE_CONTROL 1


#endif /* _ALTERA_HPS_H_ */
